app:
  id: simcart
server:
  grpc:
    host: 0.0.0.0
    port: 50051
  rest:
    host: 0.0.0.0
    port: 8080

client:
  redis:
    host: redis
    port: 6379
    user:
    password:
    db: 0

  jaeger:
    host: jaeger
    port: 6831

  postgres:
    host: postgres
    port: 5432
    user: postgres
    database: test_db
    password: changeme
  redisearch:
    host: redisearch
    port: "6379"
