app:
  id: simcart
server:
  grpc:
    host: 0.0.0.0
    port: 50051
  rest:
    host: 0.0.0.0
    port: 8080

client:
  jaeger:
    host: jaeger
    port: 6831

  postgres:
    host: postgres
    port: 5432
    user: postgres
    database: simcart
    password: changeme
  redisearch:
    host: redisearch
    port: "6379"
