kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: golang:1.16
    commands:
      - sleep 30
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_DATABASE=test_db POSTGRES_DATABASE=test_db go run . migrate create model --extensions=uuid-ossp,hstore
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD go run . seed
      - go test ./...

services:
  - name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  - name: redisearch
    image: redislabs/redisearch:2.0.0
