kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: golang:1.16
    commands:
      - go vet ./...
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_DATABASE=test_db go run . migrate create model --extensions=uuid-ossp,hstore
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_DATABASE=test_db go run . seed
      - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov-token
      files:
        - coverage.txt

services:
  - name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: changeme
  - name: redisearch
    image: redislabs/redisearch:2.0.0
