kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: golang:1.16
    commands:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD go run . migrate create models --extensions=uuid-ossp,hstore
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD go run . seed
      - go test ./...

services:
  - name: database
    image: postgres:9-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: changeme
