version: "3.9"

services:
  # -----------------------------
  # simcart
  # -----------------------------
  simcart:
    # build or use image
    build: .
    tty: true # Enables debugging capabilities when attached to this container.
    depends_on:
      - postgres
      - redisearch
    ports:
      - "50052:50051"
    networks:
      - backend
      - dbnet
      - frontend

  # -----------------------------
  # postgres database
  # -----------------------------
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: simcart
    networks:
      - dbnet
      - backend
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pg@github.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-changeme}
      PGADMIN_CONFIG_SERVER_MODE: "True"
    networks:
      - backend
      - frontend
    ports:
      - "${PGADMIN_PORT:-5050}:80"

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    depends_on:
      - simcart
    ports:
      - "8200:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - backend
      - frontend

  redisearch:
    image: redislabs/redisearch:2.0.0
    networks:
      - backend
# -----------------------------
# networks
# -----------------------------
networks:
  backend:
    external: true
  dbnet:
  frontend:
