// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: cartpb/enums.proto

package cartpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CartStatus int32

const (
	CartStatus_New               CartStatus = 0
	CartStatus_Closed            CartStatus = 1
	CartStatus_CheckedOut        CartStatus = 2
	CartStatus_Expired           CartStatus = 3
	CartStatus_WaitingForPayment CartStatus = 4
	CartStatus_Fullfilled        CartStatus = 5
	CartStatus_Delivered         CartStatus = 6
	CartStatus_Postponed         CartStatus = 7
)

// Enum value maps for CartStatus.
var (
	CartStatus_name = map[int32]string{
		0: "New",
		1: "Closed",
		2: "CheckedOut",
		3: "Expired",
		4: "WaitingForPayment",
		5: "Fullfilled",
		6: "Delivered",
		7: "Postponed",
	}
	CartStatus_value = map[string]int32{
		"New":               0,
		"Closed":            1,
		"CheckedOut":        2,
		"Expired":           3,
		"WaitingForPayment": 4,
		"Fullfilled":        5,
		"Delivered":         6,
		"Postponed":         7,
	}
)

func (x CartStatus) Enum() *CartStatus {
	p := new(CartStatus)
	*p = x
	return p
}

func (x CartStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CartStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cartpb_enums_proto_enumTypes[0].Descriptor()
}

func (CartStatus) Type() protoreflect.EnumType {
	return &file_cartpb_enums_proto_enumTypes[0]
}

func (x CartStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CartStatus.Descriptor instead.
func (CartStatus) EnumDescriptor() ([]byte, []int) {
	return file_cartpb_enums_proto_rawDescGZIP(), []int{0}
}

var File_cartpb_enums_proto protoreflect.FileDescriptor

var file_cartpb_enums_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x61, 0x72, 0x74, 0x70, 0x62, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x73, 0x69, 0x6d, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2a, 0x83, 0x01, 0x0a, 0x0a, 0x43, 0x61, 0x72, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x65, 0x77, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x64, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x57, 0x61, 0x69, 0x74, 0x69,
	0x6e, 0x67, 0x46, 0x6f, 0x72, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x10, 0x04, 0x12, 0x0e,
	0x0a, 0x0a, 0x46, 0x75, 0x6c, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x10, 0x05, 0x12, 0x0d,
	0x0a, 0x09, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x10, 0x06, 0x12, 0x0d, 0x0a,
	0x09, 0x50, 0x6f, 0x73, 0x74, 0x70, 0x6f, 0x6e, 0x65, 0x64, 0x10, 0x07, 0x42, 0x1e, 0x5a, 0x1c,
	0x73, 0x69, 0x6d, 0x63, 0x61, 0x72, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x63,
	0x61, 0x72, 0x74, 0x70, 0x62, 0x3b, 0x63, 0x61, 0x72, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cartpb_enums_proto_rawDescOnce sync.Once
	file_cartpb_enums_proto_rawDescData = file_cartpb_enums_proto_rawDesc
)

func file_cartpb_enums_proto_rawDescGZIP() []byte {
	file_cartpb_enums_proto_rawDescOnce.Do(func() {
		file_cartpb_enums_proto_rawDescData = protoimpl.X.CompressGZIP(file_cartpb_enums_proto_rawDescData)
	})
	return file_cartpb_enums_proto_rawDescData
}

var file_cartpb_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cartpb_enums_proto_goTypes = []interface{}{
	(CartStatus)(0), // 0: simcart.api.cart.CartStatus
}
var file_cartpb_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cartpb_enums_proto_init() }
func file_cartpb_enums_proto_init() {
	if File_cartpb_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cartpb_enums_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cartpb_enums_proto_goTypes,
		DependencyIndexes: file_cartpb_enums_proto_depIdxs,
		EnumInfos:         file_cartpb_enums_proto_enumTypes,
	}.Build()
	File_cartpb_enums_proto = out.File
	file_cartpb_enums_proto_rawDesc = nil
	file_cartpb_enums_proto_goTypes = nil
	file_cartpb_enums_proto_depIdxs = nil
}
