// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: cartpb/messages.proto

package cartpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	commonpb "simcart/api/pb/commonpb"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// CartRequest represents the request struct that comes from the user
// side. It may bear a non-empty cartId that would be used to manipulate the cart content.
type CartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductUUID string `protobuf:"bytes,1,opt,name=productUUID,proto3" json:"productUUID,omitempty"`
	Sku         string `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty         int32  `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	// bid or offerred price
	Bid      int64             `protobuf:"varint,4,opt,name=bid,proto3" json:"bid,omitempty"`
	CartUUID string            `protobuf:"bytes,5,opt,name=cartUUID,proto3" json:"cartUUID,omitempty"`
	Cuurency commonpb.Currency `protobuf:"varint,6,opt,name=cuurency,proto3,enum=simcart.api.common.Currency" json:"cuurency,omitempty"`
	Owner    string            `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *CartRequest) Reset() {
	*x = CartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cartpb_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartRequest) ProtoMessage() {}

func (x *CartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cartpb_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartRequest.ProtoReflect.Descriptor instead.
func (*CartRequest) Descriptor() ([]byte, []int) {
	return file_cartpb_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CartRequest) GetProductUUID() string {
	if x != nil {
		return x.ProductUUID
	}
	return ""
}

func (x *CartRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CartRequest) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *CartRequest) GetBid() int64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *CartRequest) GetCartUUID() string {
	if x != nil {
		return x.CartUUID
	}
	return ""
}

func (x *CartRequest) GetCuurency() commonpb.Currency {
	if x != nil {
		return x.Cuurency
	}
	return commonpb.Currency_USD
}

func (x *CartRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type CartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartUUID string     `protobuf:"bytes,1,opt,name=cartUUID,proto3" json:"cartUUID,omitempty"`
	Status   CartStatus `protobuf:"varint,2,opt,name=status,proto3,enum=simcart.api.cart.CartStatus" json:"status,omitempty"`
}

func (x *CartResponse) Reset() {
	*x = CartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cartpb_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartResponse) ProtoMessage() {}

func (x *CartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cartpb_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartResponse.ProtoReflect.Descriptor instead.
func (*CartResponse) Descriptor() ([]byte, []int) {
	return file_cartpb_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CartResponse) GetCartUUID() string {
	if x != nil {
		return x.CartUUID
	}
	return ""
}

func (x *CartResponse) GetStatus() CartStatus {
	if x != nil {
		return x.Status
	}
	return CartStatus_New
}

var File_cartpb_messages_proto protoreflect.FileDescriptor

var file_cartpb_messages_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x61, 0x72, 0x74, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x73, 0x69, 0x6d, 0x63, 0x61, 0x72, 0x74,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x1a, 0x12, 0x63, 0x61, 0x72, 0x74, 0x70,
	0x62, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x70, 0x62, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x01, 0x0a, 0x0b, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x55, 0x55,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x55, 0x55, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x74, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x71, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x72, 0x74, 0x55, 0x55, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x61, 0x72, 0x74, 0x55, 0x55, 0x49, 0x44, 0x12, 0x38, 0x0a, 0x08, 0x63, 0x75, 0x75, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x73, 0x69, 0x6d, 0x63,
	0x61, 0x72, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08, 0x63, 0x75, 0x75, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x60, 0x0a, 0x0c, 0x43, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x74, 0x55,
	0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x72, 0x74, 0x55,
	0x55, 0x49, 0x44, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x73, 0x69, 0x6d, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x1e, 0x5a, 0x1c, 0x73, 0x69, 0x6d,
	0x63, 0x61, 0x72, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x61, 0x72, 0x74,
	0x70, 0x62, 0x3b, 0x63, 0x61, 0x72, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_cartpb_messages_proto_rawDescOnce sync.Once
	file_cartpb_messages_proto_rawDescData = file_cartpb_messages_proto_rawDesc
)

func file_cartpb_messages_proto_rawDescGZIP() []byte {
	file_cartpb_messages_proto_rawDescOnce.Do(func() {
		file_cartpb_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_cartpb_messages_proto_rawDescData)
	})
	return file_cartpb_messages_proto_rawDescData
}

var file_cartpb_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cartpb_messages_proto_goTypes = []interface{}{
	(*CartRequest)(nil),    // 0: simcart.api.cart.CartRequest
	(*CartResponse)(nil),   // 1: simcart.api.cart.CartResponse
	(commonpb.Currency)(0), // 2: simcart.api.common.Currency
	(CartStatus)(0),        // 3: simcart.api.cart.CartStatus
}
var file_cartpb_messages_proto_depIdxs = []int32{
	2, // 0: simcart.api.cart.CartRequest.cuurency:type_name -> simcart.api.common.Currency
	3, // 1: simcart.api.cart.CartResponse.status:type_name -> simcart.api.cart.CartStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cartpb_messages_proto_init() }
func file_cartpb_messages_proto_init() {
	if File_cartpb_messages_proto != nil {
		return
	}
	file_cartpb_enums_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cartpb_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cartpb_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cartpb_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cartpb_messages_proto_goTypes,
		DependencyIndexes: file_cartpb_messages_proto_depIdxs,
		MessageInfos:      file_cartpb_messages_proto_msgTypes,
	}.Build()
	File_cartpb_messages_proto = out.File
	file_cartpb_messages_proto_rawDesc = nil
	file_cartpb_messages_proto_goTypes = nil
	file_cartpb_messages_proto_depIdxs = nil
}
