// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: cartpb/messages.proto

package cartpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	commonpb "simcart/api/pb/commonpb"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// CartRequest represents the request struct that comes from the user
// side. It may bear a non-empty cartId that would be used to manipulate the cart content.
type CartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sku string `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty uint64 `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	// bid or offerred price
	Bid      int64             `protobuf:"varint,3,opt,name=bid,proto3" json:"bid,omitempty"`
	CartUUID string            `protobuf:"bytes,4,opt,name=cartUUID,proto3" json:"cartUUID,omitempty"`
	Cuurency commonpb.Currency `protobuf:"varint,5,opt,name=cuurency,proto3,enum=simcart.api.common.Currency" json:"cuurency,omitempty"`
	Owner    string            `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	ItemId   string            `protobuf:"bytes,7,opt,name=itemId,proto3" json:"itemId,omitempty"`
}

func (x *CartRequest) Reset() {
	*x = CartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cartpb_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartRequest) ProtoMessage() {}

func (x *CartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cartpb_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartRequest.ProtoReflect.Descriptor instead.
func (*CartRequest) Descriptor() ([]byte, []int) {
	return file_cartpb_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CartRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CartRequest) GetQty() uint64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *CartRequest) GetBid() int64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *CartRequest) GetCartUUID() string {
	if x != nil {
		return x.CartUUID
	}
	return ""
}

func (x *CartRequest) GetCuurency() commonpb.Currency {
	if x != nil {
		return x.Cuurency
	}
	return commonpb.Currency_USD
}

func (x *CartRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CartRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type CartDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemUUID  string  `protobuf:"bytes,1,opt,name=itemUUID,proto3" json:"itemUUID,omitempty"`
	ProductId uint64  `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Qty       uint64  `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	Discount  float32 `protobuf:"fixed32,4,opt,name=discount,proto3" json:"discount,omitempty"`
}

func (x *CartDetail) Reset() {
	*x = CartDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cartpb_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartDetail) ProtoMessage() {}

func (x *CartDetail) ProtoReflect() protoreflect.Message {
	mi := &file_cartpb_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartDetail.ProtoReflect.Descriptor instead.
func (*CartDetail) Descriptor() ([]byte, []int) {
	return file_cartpb_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CartDetail) GetItemUUID() string {
	if x != nil {
		return x.ItemUUID
	}
	return ""
}

func (x *CartDetail) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartDetail) GetQty() uint64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *CartDetail) GetDiscount() float32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

type CartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartUUID string        `protobuf:"bytes,1,opt,name=cartUUID,proto3" json:"cartUUID,omitempty"`
	Status   CartStatus    `protobuf:"varint,2,opt,name=status,proto3,enum=simcart.api.cart.CartStatus" json:"status,omitempty"`
	Details  []*CartDetail `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
}

func (x *CartResponse) Reset() {
	*x = CartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cartpb_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartResponse) ProtoMessage() {}

func (x *CartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cartpb_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartResponse.ProtoReflect.Descriptor instead.
func (*CartResponse) Descriptor() ([]byte, []int) {
	return file_cartpb_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CartResponse) GetCartUUID() string {
	if x != nil {
		return x.CartUUID
	}
	return ""
}

func (x *CartResponse) GetStatus() CartStatus {
	if x != nil {
		return x.Status
	}
	return CartStatus_New
}

func (x *CartResponse) GetDetails() []*CartDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

type CartFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner  string       `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Status []CartStatus `protobuf:"varint,2,rep,packed,name=status,proto3,enum=simcart.api.cart.CartStatus" json:"status,omitempty"`
}

func (x *CartFilter) Reset() {
	*x = CartFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cartpb_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartFilter) ProtoMessage() {}

func (x *CartFilter) ProtoReflect() protoreflect.Message {
	mi := &file_cartpb_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartFilter.ProtoReflect.Descriptor instead.
func (*CartFilter) Descriptor() ([]byte, []int) {
	return file_cartpb_messages_proto_rawDescGZIP(), []int{3}
}

func (x *CartFilter) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CartFilter) GetStatus() []CartStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type CartRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*CartResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *CartRequests) Reset() {
	*x = CartRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cartpb_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartRequests) ProtoMessage() {}

func (x *CartRequests) ProtoReflect() protoreflect.Message {
	mi := &file_cartpb_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartRequests.ProtoReflect.Descriptor instead.
func (*CartRequests) Descriptor() ([]byte, []int) {
	return file_cartpb_messages_proto_rawDescGZIP(), []int{4}
}

func (x *CartRequests) GetResponses() []*CartResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type CheckoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartUUID   string `protobuf:"bytes,1,opt,name=cartUUID,proto3" json:"cartUUID,omitempty"`
	Refrence   string `protobuf:"bytes,2,opt,name=refrence,proto3" json:"refrence,omitempty"`
	PaymentUrl string `protobuf:"bytes,3,opt,name=paymentUrl,proto3" json:"paymentUrl,omitempty"`
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cartpb_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cartpb_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_cartpb_messages_proto_rawDescGZIP(), []int{5}
}

func (x *CheckoutResponse) GetCartUUID() string {
	if x != nil {
		return x.CartUUID
	}
	return ""
}

func (x *CheckoutResponse) GetRefrence() string {
	if x != nil {
		return x.Refrence
	}
	return ""
}

func (x *CheckoutResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

var File_cartpb_messages_proto protoreflect.FileDescriptor

var file_cartpb_messages_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x61, 0x72, 0x74, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x73, 0x69, 0x6d, 0x63, 0x61, 0x72, 0x74,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x1a, 0x12, 0x63, 0x61, 0x72, 0x74, 0x70,
	0x62, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x70, 0x62, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xc7, 0x01, 0x0a, 0x0b, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x71, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x72,
	0x74, 0x55, 0x55, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x72,
	0x74, 0x55, 0x55, 0x49, 0x44, 0x12, 0x38, 0x0a, 0x08, 0x63, 0x75, 0x75, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x73, 0x69, 0x6d, 0x63, 0x61, 0x72,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08, 0x63, 0x75, 0x75, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x74, 0x0a,
	0x0a, 0x43, 0x61, 0x72, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x74, 0x65, 0x6d, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69,
	0x74, 0x65, 0x6d, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x71, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x98, 0x01, 0x0a, 0x0c, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x74, 0x55, 0x55, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x72, 0x74, 0x55, 0x55, 0x49, 0x44,
	0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1c, 0x2e, 0x73, 0x69, 0x6d, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x36, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x69, 0x6d, 0x63, 0x61, 0x72,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x58,
	0x0a, 0x0a, 0x43, 0x61, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x73, 0x69, 0x6d, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4c, 0x0a, 0x0c, 0x43, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x3c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x69,
	0x6d, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x09, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x6a, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x72, 0x74, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61,
	0x72, 0x74, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x66, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x66, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x72, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x55,
	0x72, 0x6c, 0x42, 0x1e, 0x5a, 0x1c, 0x73, 0x69, 0x6d, 0x63, 0x61, 0x72, 0x74, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x70, 0x62, 0x3b, 0x63, 0x61, 0x72, 0x74,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cartpb_messages_proto_rawDescOnce sync.Once
	file_cartpb_messages_proto_rawDescData = file_cartpb_messages_proto_rawDesc
)

func file_cartpb_messages_proto_rawDescGZIP() []byte {
	file_cartpb_messages_proto_rawDescOnce.Do(func() {
		file_cartpb_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_cartpb_messages_proto_rawDescData)
	})
	return file_cartpb_messages_proto_rawDescData
}

var file_cartpb_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cartpb_messages_proto_goTypes = []interface{}{
	(*CartRequest)(nil),      // 0: simcart.api.cart.CartRequest
	(*CartDetail)(nil),       // 1: simcart.api.cart.CartDetail
	(*CartResponse)(nil),     // 2: simcart.api.cart.CartResponse
	(*CartFilter)(nil),       // 3: simcart.api.cart.CartFilter
	(*CartRequests)(nil),     // 4: simcart.api.cart.CartRequests
	(*CheckoutResponse)(nil), // 5: simcart.api.cart.CheckoutResponse
	(commonpb.Currency)(0),   // 6: simcart.api.common.Currency
	(CartStatus)(0),          // 7: simcart.api.cart.CartStatus
}
var file_cartpb_messages_proto_depIdxs = []int32{
	6, // 0: simcart.api.cart.CartRequest.cuurency:type_name -> simcart.api.common.Currency
	7, // 1: simcart.api.cart.CartResponse.status:type_name -> simcart.api.cart.CartStatus
	1, // 2: simcart.api.cart.CartResponse.details:type_name -> simcart.api.cart.CartDetail
	7, // 3: simcart.api.cart.CartFilter.status:type_name -> simcart.api.cart.CartStatus
	2, // 4: simcart.api.cart.CartRequests.responses:type_name -> simcart.api.cart.CartResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cartpb_messages_proto_init() }
func file_cartpb_messages_proto_init() {
	if File_cartpb_messages_proto != nil {
		return
	}
	file_cartpb_enums_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cartpb_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cartpb_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cartpb_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cartpb_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cartpb_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cartpb_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cartpb_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cartpb_messages_proto_goTypes,
		DependencyIndexes: file_cartpb_messages_proto_depIdxs,
		MessageInfos:      file_cartpb_messages_proto_msgTypes,
	}.Build()
	File_cartpb_messages_proto = out.File
	file_cartpb_messages_proto_rawDesc = nil
	file_cartpb_messages_proto_goTypes = nil
	file_cartpb_messages_proto_depIdxs = nil
}
